#!/usr/bin/env ruby

$LOAD_PATH << "lib"
$LOAD_PATH << "models"

require 'environment'
Environment.environment = "test"

require 'injury'

def menu
<<EOS
What do you want to do?
1. Add Person
2. Add Injury
3. Evaluate Injured Person
EOS
end

def add_injury
  puts "What is the injury you want to add?"
  injury_name = gets.chomp
  Injury.new(injury_name).save
  puts "#{injury_name} has been added."
end

def get_menu_selection
  puts menu
  input = gets
  return unless input
  input.chomp!
  if input == "1"
    puts "Who do you want to add?"
  elsif input == "2"
    add_injury
  elsif input == "3"
    puts "Who is injured?"
  else
    puts "'#{input}' is not a valid selection"
    get_menu_selection
  end
end

get_menu_selection
